export const authToken =
  'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..iPjCevERqpYuEFjG.nodNKcrXVEeovwaCGksr_fOzuvyxmj0hIsW1tmVQzvQOJD9EOllC-r-wLV9xsja6vFjuFgFRccm1IGibiqieTvKroT78skCLNn8eQeQFqiXSLgYy30UUttQ9Ol3h0pvcM_WhOYWZ3lafmF39lEXH7ynvr5wdqprOgfGcJtNiL-TLsE4AS1qZtNTVPaDwDEoImObxyH9NjGVKzJSDJWh5QLUXPJfgLMo.EOreFAqdgMbxSH0HOGTevw';
